# Generated by Django 5.2.1 on 2025-05-09 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, unique=True, verbose_name='Ders Adı')),
            ],
            options={
                'verbose_name': 'Ders',
                'verbose_name_plural': 'Dersler',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='Sinav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, verbose_name='Sınav Adı')),
                ('tarih', models.DateField(blank=True, null=True, verbose_name='Sınav Tarihi')),
            ],
            options={
                'verbose_name': 'Sınav',
                'verbose_name_plural': 'Sınavlar',
                'ordering': ['-tarih', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='Ogrenci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kimlik_id', models.CharField(help_text='Öğrencinin benzersiz kimliği. Kullanıcı adı olarak da kullanılabilir.', max_length=50, unique=True, verbose_name='Öğrenci Kimlik ID')),
                ('ad_soyad', models.CharField(max_length=150, verbose_name='Adı Soyadı')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı Hesabı')),
            ],
            options={
                'verbose_name': 'Öğrenci',
                'verbose_name_plural': 'Öğrenciler',
                'ordering': ['ad_soyad'],
            },
        ),
        migrations.CreateModel(
            name='Sonuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dogru_sayisi', models.PositiveIntegerField(verbose_name='Doğru Sayısı')),
                ('yanlis_sayisi', models.PositiveIntegerField(verbose_name='Yanlış Sayısı')),
                ('bos_sayisi', models.PositiveIntegerField(verbose_name='Boş Sayısı')),
                ('net_puan', models.FloatField(verbose_name='Net Puan')),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonuclar.ders', verbose_name='Ders')),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonuclar.ogrenci', verbose_name='Öğrenci')),
                ('sinav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonuclar.sinav', verbose_name='Sınav')),
            ],
            options={
                'verbose_name': 'Sınav Sonucu',
                'verbose_name_plural': 'Sınav Sonuçları',
                'ordering': ['-sinav__tarih', 'ogrenci__ad_soyad', 'ders__ad'],
                'unique_together': {('ogrenci', 'sinav', 'ders')},
            },
        ),
    ]
