# Generated by Django 5.2.1 on 2025-05-09 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonuclar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Konu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unite_adi', models.CharField(max_length=200, verbose_name='Ünite Adı')),
                ('konu_adi', models.CharField(max_length=300, verbose_name='Konu/Kazanım Adı')),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonuclar.ders', verbose_name='Ders')),
            ],
            options={
                'verbose_name': 'Konu/Kazanım',
                'verbose_name_plural': 'Konular/Kazanımlar',
                'ordering': ['ders__ad', 'unite_adi', 'konu_adi'],
                'unique_together': {('ders', 'unite_adi', 'konu_adi')},
            },
        ),
        migrations.CreateModel(
            name='OgrenciYanlisDetayi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yanlis_adedi', models.PositiveIntegerField(default=1, verbose_name='Bu Konudaki Yanlış Adedi')),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonuclar.ders', verbose_name='Ders')),
                ('konu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonuclar.konu', verbose_name='Konu/Kazanım')),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonuclar.ogrenci', verbose_name='Öğrenci')),
                ('sinav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonuclar.sinav', verbose_name='Sınav')),
            ],
            options={
                'verbose_name': 'Öğrenci Yanlış Detayı',
                'verbose_name_plural': 'Öğrenci Yanlış Detayları',
                'ordering': ['-sinav__tarih', 'ogrenci__ad_soyad', 'konu__ders__ad', 'konu__unite_adi', 'konu__konu_adi'],
                'unique_together': {('ogrenci', 'sinav', 'konu')},
            },
        ),
    ]
